"$schema" = 'https://starship.rs/config-schema.json'

# [character]
# success_symbol = "[❯](bold yellow)"
# error_symbol = "[❯](bold red)"

[git_branch]
symbol = " "
style = "bold orange"

[aws]
disabled = true
[lua]
disabled = true
